name: Build Repo
on:
  workflow_call:

permissions:
  contents: write

jobs:

  build-project:
    runs-on: ubuntu-latest
    if: >-
      ${{ !github.event.repository.is_template
          && needs.matrix_file_exist.outputs.state != ''}}
    strategy:
      matrix: ${{ fromJSON(needs.matrix_file_exist.outputs.file) }}
    outputs:
      buildVersion: ${{ steps.buildStep.outputs.buildVersion }}
    name: Build project for  ${{ matrix.platformName }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: ${{ matrix.platformName }}'s external file
        uses: ./.github/script/build-workflow
        with:
          platform: ${{ matrix.platformName }}
          targetPlatform: ${{ matrix.targetPlatform }}
          configFile: ${{ matrix.configFile }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}