name: Build Repo
on: 
  workflow_call:
    inputs:
      matrix-file:
        description: 'Matrix file'
        required: true
        type: string
      formatted-name:
        description: 'Project name formatted'
        required: true
        type: string
      version:
        description: 'Project version'
        required: true
        type: string

permissions:
  contents: write

jobs:

  build-project:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(inputs.matrix-file) }}
    name: Build project for  ${{ matrix.platformName }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Print version
        run: |
          echo ${{ inputs.version }}
        shell: bash
      - name: ${{ matrix.platformName }} external file
        uses: ./.github/script/build-workflow
        with:
          platform: ${{ matrix.platformName }}
          target-platform: ${{ matrix.targetPlatform }}
          config-file: ${{ matrix.configFile }}
          formatted-name: ${{ inputs.formatted-name }}
          version: ${{ inputs.version }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEY_ALIAS_NAME: ${{ secrets.KEY_ALIAS_NAME }}
          KEY_ALIAS_PASS: ${{ secrets.KEY_ALIAS_PASS }}
            