name: Build Repo
on: 
  workflow_call:
    inputs:
      matrix-file:
        description: 'Matrix file'
        required: true
        type: string

permissions:
  contents: write

jobs:

  build-project:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(inputs.matrix-file) }}
    outputs:
      buildVersion: ${{ steps.buildStep.outputs.buildVersion }}
    name: Build project for  ${{ matrix.platformName }}
    steps:
      - name: ${{ matrix.platformName }} external file
        uses: ./.github/script/build-workflow
        with:
          platform: ${{ matrix.platformName }}
          target-platform: ${{ matrix.targetPlatform }}
          config-file: ${{ matrix.configFile }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}