name: Upload Build
on: 
  workflow_call:
    inputs:
      matrix-file:
        description: 'Matrix file'
        required: true
        type: string
      project-name:
        description: "Project name"
        required: true
        type: string
      client-name:
        description: "Client name"
        required: true
        type: string

permissions:
  contents: write

jobs:

  build-project:
    runs-on: ubuntu-latest
    # if: >-
    #   ${{ !github.event.repository.is_template }}
    strategy:
      matrix: ${{ fromJSON(inputs.matrix-file) }}
    outputs:
      buildVersion: ${{ steps.buildStep.outputs.buildVersion }}
    name: Upload build for  ${{ matrix.platformName }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: ${{ matrix.platformName }} external file
        uses: ./.github/script/build-workflow
        with:
          platform: ${{ matrix.platformName }}
          AWS_KEY: ${{ secrets.AWS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          project-name: ${{ inputs.project-name }}  
          client-name: ${{ inputs.client-name }}  